# ============================
# MYSQL Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-config
      tolerations:
        - key: db
          value: only
          effect: NoSchedule
