apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        resources: {}

